[manager]
ratio          = [ 1, 4, 3 ]
sort_by        = "modified"
sort_sensitive = false
sort_reverse 	 = false
sort_dir_first = true
sort_translit  = false
linemode       = "size"
show_hidden    = true
